spring:
  application:
    name: book-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mvc:
    servlet:
      path: /api


server:
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}