spring:
  application:
    name: book-api

  datasource:
    url: ${DB_URL}
    username: root
    password: 111111

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  mvc:
    servlet:
      path: /api


server:
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}